// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_token.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO access_tokens (user_id, name, token_hash, prefix, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, token_hash, prefix, status, expires_at, created_at
`

type CreateAccessTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	TokenHash string             `json:"token_hash"`
	Prefix    string             `json:"prefix"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error) {
	row := q.db.QueryRow(ctx, createAccessToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.ExpiresAt,
	)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccessTokenByHash = `-- name: GetAccessTokenByHash :one
SELECT id, user_id, name, token_hash, prefix, status, expires_at, created_at
FROM access_tokens
WHERE token_hash = $1
`

func (q *Queries) GetAccessTokenByHash(ctx context.Context, tokenHash string) (AccessToken, error) {
	row := q.db.QueryRow(ctx, getAccessTokenByHash, tokenHash)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAccessTokensByUserID = `-- name: ListAccessTokensByUserID :many
SELECT id, user_id, name, token_hash, prefix, status, expires_at, created_at
FROM access_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAccessTokensByUserID(ctx context.Context, userID pgtype.UUID) ([]AccessToken, error) {
	rows, err := q.db.Query(ctx, listAccessTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessToken{}
	for rows.Next() {
		var i AccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadAllActiveAccessTokens = `-- name: LoadAllActiveAccessTokens :many
SELECT id, user_id, name, token_hash, prefix, status, expires_at, created_at
FROM access_tokens
WHERE status = 'active'
`

func (q *Queries) LoadAllActiveAccessTokens(ctx context.Context) ([]AccessToken, error) {
	rows, err := q.db.Query(ctx, loadAllActiveAccessTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessToken{}
	for rows.Next() {
		var i AccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccessTokensExpiredBatch = `-- name: MarkAccessTokensExpiredBatch :exec
UPDATE access_tokens
SET status = 'expired'
WHERE id = ANY($1::uuid[])
`

func (q *Queries) MarkAccessTokensExpiredBatch(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAccessTokensExpiredBatch, dollar_1)
	return err
}

const updateAccessTokenStatus = `-- name: UpdateAccessTokenStatus :exec
UPDATE access_tokens
SET status = $2
WHERE id = $1
`

type UpdateAccessTokenStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateAccessTokenStatus(ctx context.Context, arg UpdateAccessTokenStatusParams) error {
	_, err := q.db.Exec(ctx, updateAccessTokenStatus, arg.ID, arg.Status)
	return err
}
