// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entry.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAccessibleEntries = `-- name: CountAccessibleEntries :one
SELECT count(*) FROM entries
WHERE visibility = 'public' OR user_id = $1
`

func (q *Queries) CountAccessibleEntries(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccessibleEntries, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccessibleEntriesByPath = `-- name: CountAccessibleEntriesByPath :one
SELECT count(*) FROM entries
WHERE (visibility = 'public' OR user_id = $1)
  AND (path = $2 OR path LIKE $2 || '/%')
`

type CountAccessibleEntriesByPathParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Path   string      `json:"path"`
}

func (q *Queries) CountAccessibleEntriesByPath(ctx context.Context, arg CountAccessibleEntriesByPathParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccessibleEntriesByPath, arg.UserID, arg.Path)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEntriesByUser = `-- name: CountEntriesByUser :one
SELECT count(*) FROM entries WHERE user_id = $1
`

func (q *Queries) CountEntriesByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEntriesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEntriesInPath = `-- name: CountEntriesInPath :one
SELECT count(*) FROM entries e
WHERE 
  CASE 
    WHEN $1::boolean THEN e.user_id = $2::uuid
    ELSE (e.visibility = 'public' OR e.user_id = $2::uuid)
  END
  AND e.path = $3::text
  AND (
    $4::text IS NULL OR 
    $4::text = '' OR 
    e.visibility = $4::text
  )
  AND (
    $5::timestamptz IS NULL OR 
    e.created_at >= $5::timestamptz
  )
  AND (
    $6::timestamptz IS NULL OR 
    e.created_at <= $6::timestamptz
  )
  AND (
    $7::text[] IS NULL OR
    $7::text[] = '{}' OR
    EXISTS (
      SELECT 1 FROM entry_tags et
      JOIN tags t ON t.id = et.tag_id
      WHERE et.entry_id = e.id AND t.name = ANY($7::text[])
    )
  )
`

type CountEntriesInPathParams struct {
	Own              bool               `json:"own"`
	UserID           pgtype.UUID        `json:"user_id"`
	Path             string             `json:"path"`
	FilterVisibility string             `json:"filter_visibility"`
	FromDate         pgtype.Timestamptz `json:"from_date"`
	ToDate           pgtype.Timestamptz `json:"to_date"`
	FilterTags       []string           `json:"filter_tags"`
}

func (q *Queries) CountEntriesInPath(ctx context.Context, arg CountEntriesInPathParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEntriesInPath,
		arg.Own,
		arg.UserID,
		arg.Path,
		arg.FilterVisibility,
		arg.FromDate,
		arg.ToDate,
		arg.FilterTags,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries WHERE id = $1
`

func (q *Queries) DeleteEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEntry, id)
	return err
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT id, user_id, title, content, summary, s3_key, path, visibility, file_type, file_size, embedding, created_at, updated_at
FROM entries
WHERE id = $1
`

type GetEntryByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Summary    string             `json:"summary"`
	S3Key      string             `json:"s3_key"`
	Path       string             `json:"path"`
	Visibility string             `json:"visibility"`
	FileType   string             `json:"file_type"`
	FileSize   int64              `json:"file_size"`
	Embedding  pgtype.Text        `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEntryByID(ctx context.Context, id pgtype.UUID) (GetEntryByIDRow, error) {
	row := q.db.QueryRow(ctx, getEntryByID, id)
	var i GetEntryByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.S3Key,
		&i.Path,
		&i.Visibility,
		&i.FileType,
		&i.FileSize,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEntry = `-- name: InsertEntry :one
INSERT INTO entries (user_id, title, content, summary, s3_key, path, visibility, file_type, file_size, embedding)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, title, content, summary, s3_key, path, visibility, file_type, file_size, embedding, created_at, updated_at
`

type InsertEntryParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Title      string      `json:"title"`
	Content    string      `json:"content"`
	Summary    string      `json:"summary"`
	S3Key      string      `json:"s3_key"`
	Path       string      `json:"path"`
	Visibility string      `json:"visibility"`
	FileType   string      `json:"file_type"`
	FileSize   int64       `json:"file_size"`
	Embedding  pgtype.Text `json:"embedding"`
}

type InsertEntryRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Summary    string             `json:"summary"`
	S3Key      string             `json:"s3_key"`
	Path       string             `json:"path"`
	Visibility string             `json:"visibility"`
	FileType   string             `json:"file_type"`
	FileSize   int64              `json:"file_size"`
	Embedding  pgtype.Text        `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (InsertEntryRow, error) {
	row := q.db.QueryRow(ctx, insertEntry,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.S3Key,
		arg.Path,
		arg.Visibility,
		arg.FileType,
		arg.FileSize,
		arg.Embedding,
	)
	var i InsertEntryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.S3Key,
		&i.Path,
		&i.Visibility,
		&i.FileType,
		&i.FileSize,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccessibleEntries = `-- name: ListAccessibleEntries :many
SELECT id, user_id, title, content, summary, s3_key, path, visibility, file_type, file_size, embedding, created_at, updated_at
FROM entries
WHERE (visibility = 'public' OR user_id = $1)
ORDER BY path ASC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListAccessibleEntriesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListAccessibleEntriesRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Summary    string             `json:"summary"`
	S3Key      string             `json:"s3_key"`
	Path       string             `json:"path"`
	Visibility string             `json:"visibility"`
	FileType   string             `json:"file_type"`
	FileSize   int64              `json:"file_size"`
	Embedding  pgtype.Text        `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAccessibleEntries(ctx context.Context, arg ListAccessibleEntriesParams) ([]ListAccessibleEntriesRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleEntries, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessibleEntriesRow{}
	for rows.Next() {
		var i ListAccessibleEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.S3Key,
			&i.Path,
			&i.Visibility,
			&i.FileType,
			&i.FileSize,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessibleEntriesByPath = `-- name: ListAccessibleEntriesByPath :many
SELECT id, user_id, title, content, summary, s3_key, path, visibility, file_type, file_size, embedding, created_at, updated_at
FROM entries
WHERE (visibility = 'public' OR user_id = $1)
  AND (path = $2 OR path LIKE $2 || '/%')
ORDER BY path ASC, created_at DESC
LIMIT $3 OFFSET $4
`

type ListAccessibleEntriesByPathParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Path   string      `json:"path"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListAccessibleEntriesByPathRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Summary    string             `json:"summary"`
	S3Key      string             `json:"s3_key"`
	Path       string             `json:"path"`
	Visibility string             `json:"visibility"`
	FileType   string             `json:"file_type"`
	FileSize   int64              `json:"file_size"`
	Embedding  pgtype.Text        `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAccessibleEntriesByPath(ctx context.Context, arg ListAccessibleEntriesByPathParams) ([]ListAccessibleEntriesByPathRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleEntriesByPath,
		arg.UserID,
		arg.Path,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessibleEntriesByPathRow{}
	for rows.Next() {
		var i ListAccessibleEntriesByPathRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.S3Key,
			&i.Path,
			&i.Visibility,
			&i.FileType,
			&i.FileSize,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllEntries = `-- name: ListAllEntries :many
SELECT id, user_id, title, content, summary, s3_key, path, visibility, file_type, file_size, embedding, created_at, updated_at
FROM entries
ORDER BY created_at ASC
`

type ListAllEntriesRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Summary    string             `json:"summary"`
	S3Key      string             `json:"s3_key"`
	Path       string             `json:"path"`
	Visibility string             `json:"visibility"`
	FileType   string             `json:"file_type"`
	FileSize   int64              `json:"file_size"`
	Embedding  pgtype.Text        `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAllEntries(ctx context.Context) ([]ListAllEntriesRow, error) {
	rows, err := q.db.Query(ctx, listAllEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllEntriesRow{}
	for rows.Next() {
		var i ListAllEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.S3Key,
			&i.Path,
			&i.Visibility,
			&i.FileType,
			&i.FileSize,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPaths = `-- name: ListAllPaths :many
SELECT DISTINCT e.path FROM entries e
WHERE 
  CASE 
    WHEN $1::boolean THEN e.user_id = $2::uuid
    ELSE (e.visibility = 'public' OR e.user_id = $2::uuid)
  END
  AND (
    $3::text IS NULL OR 
    $3::text = '' OR 
    e.visibility = $3::text
  )
  AND (
    $4::timestamptz IS NULL OR 
    e.created_at >= $4::timestamptz
  )
  AND (
    $5::timestamptz IS NULL OR 
    e.created_at <= $5::timestamptz
  )
  AND (
    $6::text[] IS NULL OR
    $6::text[] = '{}' OR
    EXISTS (
      SELECT 1 FROM entry_tags et
      JOIN tags t ON t.id = et.tag_id
      WHERE et.entry_id = e.id AND t.name = ANY($6::text[])
    )
  )
ORDER BY e.path ASC
`

type ListAllPathsParams struct {
	Own              bool               `json:"own"`
	UserID           pgtype.UUID        `json:"user_id"`
	FilterVisibility string             `json:"filter_visibility"`
	FromDate         pgtype.Timestamptz `json:"from_date"`
	ToDate           pgtype.Timestamptz `json:"to_date"`
	FilterTags       []string           `json:"filter_tags"`
}

func (q *Queries) ListAllPaths(ctx context.Context, arg ListAllPathsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllPaths,
		arg.Own,
		arg.UserID,
		arg.FilterVisibility,
		arg.FromDate,
		arg.ToDate,
		arg.FilterTags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctPaths = `-- name: ListDistinctPaths :many
SELECT DISTINCT path FROM entries
WHERE (visibility = 'public' OR user_id = $1::uuid)
ORDER BY path ASC
`

func (q *Queries) ListDistinctPaths(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctPaths, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByUser = `-- name: ListEntriesByUser :many
SELECT id, user_id, title, content, summary, s3_key, path, visibility, file_type, file_size, embedding, created_at, updated_at
FROM entries
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEntriesByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListEntriesByUserRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Summary    string             `json:"summary"`
	S3Key      string             `json:"s3_key"`
	Path       string             `json:"path"`
	Visibility string             `json:"visibility"`
	FileType   string             `json:"file_type"`
	FileSize   int64              `json:"file_size"`
	Embedding  pgtype.Text        `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEntriesByUser(ctx context.Context, arg ListEntriesByUserParams) ([]ListEntriesByUserRow, error) {
	rows, err := q.db.Query(ctx, listEntriesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesByUserRow{}
	for rows.Next() {
		var i ListEntriesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.S3Key,
			&i.Path,
			&i.Visibility,
			&i.FileType,
			&i.FileSize,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesInPath = `-- name: ListEntriesInPath :many
SELECT e.id, e.user_id, e.title, e.content, e.summary, e.s3_key, e.path, e.visibility, e.file_type, e.file_size, e.embedding, e.created_at, e.updated_at
FROM entries e
WHERE 
  CASE 
    WHEN $1::boolean THEN e.user_id = $2::uuid
    ELSE (e.visibility = 'public' OR e.user_id = $2::uuid)
  END
  AND e.path = $3::text
  AND (
    $4::text IS NULL OR 
    $4::text = '' OR 
    e.visibility = $4::text
  )
  AND (
    $5::timestamptz IS NULL OR 
    e.created_at >= $5::timestamptz
  )
  AND (
    $6::timestamptz IS NULL OR 
    e.created_at <= $6::timestamptz
  )
  AND (
    $7::text[] IS NULL OR
    $7::text[] = '{}' OR
    EXISTS (
      SELECT 1 FROM entry_tags et
      JOIN tags t ON t.id = et.tag_id
      WHERE et.entry_id = e.id AND t.name = ANY($7::text[])
    )
  )
ORDER BY e.created_at DESC
LIMIT $9::int OFFSET $8::int
`

type ListEntriesInPathParams struct {
	Own              bool               `json:"own"`
	UserID           pgtype.UUID        `json:"user_id"`
	Path             string             `json:"path"`
	FilterVisibility string             `json:"filter_visibility"`
	FromDate         pgtype.Timestamptz `json:"from_date"`
	ToDate           pgtype.Timestamptz `json:"to_date"`
	FilterTags       []string           `json:"filter_tags"`
	Offset           int32              `json:"offset"`
	Limit            int32              `json:"limit"`
}

type ListEntriesInPathRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Summary    string             `json:"summary"`
	S3Key      string             `json:"s3_key"`
	Path       string             `json:"path"`
	Visibility string             `json:"visibility"`
	FileType   string             `json:"file_type"`
	FileSize   int64              `json:"file_size"`
	Embedding  pgtype.Text        `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEntriesInPath(ctx context.Context, arg ListEntriesInPathParams) ([]ListEntriesInPathRow, error) {
	rows, err := q.db.Query(ctx, listEntriesInPath,
		arg.Own,
		arg.UserID,
		arg.Path,
		arg.FilterVisibility,
		arg.FromDate,
		arg.ToDate,
		arg.FilterTags,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesInPathRow{}
	for rows.Next() {
		var i ListEntriesInPathRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.S3Key,
			&i.Path,
			&i.Visibility,
			&i.FileType,
			&i.FileSize,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPathsUnderPrefix = `-- name: ListPathsUnderPrefix :many
SELECT DISTINCT e.path FROM entries e
WHERE 
  CASE 
    WHEN $1::boolean THEN e.user_id = $2::uuid
    ELSE (e.visibility = 'public' OR e.user_id = $2::uuid)
  END
  AND e.path LIKE $3::text || '/%'
  AND (
    $4::text IS NULL OR 
    $4::text = '' OR 
    e.visibility = $4::text
  )
  AND (
    $5::timestamptz IS NULL OR 
    e.created_at >= $5::timestamptz
  )
  AND (
    $6::timestamptz IS NULL OR 
    e.created_at <= $6::timestamptz
  )
  AND (
    $7::text[] IS NULL OR
    $7::text[] = '{}' OR
    EXISTS (
      SELECT 1 FROM entry_tags et
      JOIN tags t ON t.id = et.tag_id
      WHERE et.entry_id = e.id AND t.name = ANY($7::text[])
    )
  )
ORDER BY e.path ASC
`

type ListPathsUnderPrefixParams struct {
	Own              bool               `json:"own"`
	UserID           pgtype.UUID        `json:"user_id"`
	Prefix           string             `json:"prefix"`
	FilterVisibility string             `json:"filter_visibility"`
	FromDate         pgtype.Timestamptz `json:"from_date"`
	ToDate           pgtype.Timestamptz `json:"to_date"`
	FilterTags       []string           `json:"filter_tags"`
}

func (q *Queries) ListPathsUnderPrefix(ctx context.Context, arg ListPathsUnderPrefixParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPathsUnderPrefix,
		arg.Own,
		arg.UserID,
		arg.Prefix,
		arg.FilterVisibility,
		arg.FromDate,
		arg.ToDate,
		arg.FilterTags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries
SET title = $2, content = $3, summary = $4, s3_key = $5, path = $6, visibility = $7, file_type = $8, file_size = $9, embedding = $10, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, content, summary, s3_key, path, visibility, file_type, file_size, embedding, created_at, updated_at
`

type UpdateEntryParams struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	Content    string      `json:"content"`
	Summary    string      `json:"summary"`
	S3Key      string      `json:"s3_key"`
	Path       string      `json:"path"`
	Visibility string      `json:"visibility"`
	FileType   string      `json:"file_type"`
	FileSize   int64       `json:"file_size"`
	Embedding  pgtype.Text `json:"embedding"`
}

type UpdateEntryRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Summary    string             `json:"summary"`
	S3Key      string             `json:"s3_key"`
	Path       string             `json:"path"`
	Visibility string             `json:"visibility"`
	FileType   string             `json:"file_type"`
	FileSize   int64              `json:"file_size"`
	Embedding  pgtype.Text        `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (UpdateEntryRow, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.S3Key,
		arg.Path,
		arg.Visibility,
		arg.FileType,
		arg.FileSize,
		arg.Embedding,
	)
	var i UpdateEntryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.S3Key,
		&i.Path,
		&i.Visibility,
		&i.FileType,
		&i.FileSize,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEntryEmbedding = `-- name: UpdateEntryEmbedding :exec
UPDATE entries SET embedding = $2, updated_at = now() WHERE id = $1
`

type UpdateEntryEmbeddingParams struct {
	ID        pgtype.UUID `json:"id"`
	Embedding pgtype.Text `json:"embedding"`
}

func (q *Queries) UpdateEntryEmbedding(ctx context.Context, arg UpdateEntryEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateEntryEmbedding, arg.ID, arg.Embedding)
	return err
}
