// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachTagToEntry = `-- name: AttachTagToEntry :exec
INSERT INTO entry_tags (entry_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AttachTagToEntryParams struct {
	EntryID pgtype.UUID `json:"entry_id"`
	TagID   pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AttachTagToEntry(ctx context.Context, arg AttachTagToEntryParams) error {
	_, err := q.db.Exec(ctx, attachTagToEntry, arg.EntryID, arg.TagID)
	return err
}

const countTags = `-- name: CountTags :one
SELECT count(*) FROM tags
`

func (q *Queries) CountTags(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const detachTagFromEntry = `-- name: DetachTagFromEntry :exec
DELETE FROM entry_tags
WHERE entry_id = $1 AND tag_id = $2
`

type DetachTagFromEntryParams struct {
	EntryID pgtype.UUID `json:"entry_id"`
	TagID   pgtype.UUID `json:"tag_id"`
}

func (q *Queries) DetachTagFromEntry(ctx context.Context, arg DetachTagFromEntryParams) error {
	_, err := q.db.Exec(ctx, detachTagFromEntry, arg.EntryID, arg.TagID)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, slug, created_at
FROM tags
WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id pgtype.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, name, slug, created_at
FROM tags
WHERE slug = $1
`

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagBySlug, slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :one
INSERT INTO tags (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at
`

type InsertTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, insertTag, arg.Name, arg.Slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, slug, created_at
FROM tags
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListTagsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByEntry = `-- name: ListTagsByEntry :many
SELECT t.id, t.name, t.slug, t.created_at
FROM tags t
INNER JOIN entry_tags et ON et.tag_id = t.id
WHERE et.entry_id = $1
ORDER BY t.name
`

func (q *Queries) ListTagsByEntry(ctx context.Context, entryID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
