// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, kratos_id, email, display_name, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByKratosID = `-- name: GetUserByKratosID :one
SELECT id, kratos_id, email, display_name, created_at
FROM users
WHERE kratos_id = $1
`

func (q *Queries) GetUserByKratosID(ctx context.Context, kratosID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByKratosID, kratosID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (kratos_id, email, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (kratos_id)
DO UPDATE SET email = EXCLUDED.email, display_name = EXCLUDED.display_name
RETURNING id, kratos_id, email, display_name, created_at
`

type UpsertUserParams struct {
	KratosID    string `json:"kratos_id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.KratosID, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}
